# Generated by Django 4.1.3 on 2023-07-17 07:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='group_images')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('posts', models.ManyToManyField(related_name='groups', to='common.post')),
                ('users', models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
