# Generated by Django 4.1.3 on 2023-08-09 05:53

import bmw_club_bg.groups.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(upload_to='group_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), bmw_club_bg.groups.models.validate_image_size]),
        ),
    ]
